name: Build Tango 2 Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - tango2-ghst

jobs:
  build-tango:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/raphaelcoeffic/opentx-commit-tests

    steps:
      - name: Checkout FreedomTX
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure Tango 2
        run: |
          mkdir -p build-tango
          cd build-tango

          cmake \
            -DDISABLE_COMPANION=YES \
            -DCMAKE_BUILD_TYPE=Release \
            -DPCB=TANGO \
            -DHELI=YES \
            -DLUA=YES \
            -DGVARS=YES \
            -DCROSSFIRE=ON \
            ..

      - name: Build Tango 2 firmware
        run: |
          cd build-tango
          make -j2 firmware

      - name: Show firmware information
        run: |
          ls -lh build-tango/firmware.bin
          sha256sum build-tango/firmware.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tango2-stock-firmware
          path: build-tango/firmware.bin
          if-no-files-found: error